export enum ActionType {
  MOVE_CELL = 'move_cell',
  DELETE_CELL = 'delete_cell',
  INSERT_CELL_AFTER = 'inser_cell_after',
  UPDATE_CELL = 'update_cell',
  BUNDLE_START = 'bundle_start',
  BUNDLE_COMPLETE = 'bundle_complete',
  FETCH_CELLS = 'fetch_cells',
  FETCH_CELLS_COMPLETE = 'fetch_cells_complete',
  FETCH_CELLS_ERROR = 'fetch_cells_error',
  SAVE_CELLS_ERROR = 'save_cells_error',
  TOGGLE_THEME = 'toggle_theme',
  CREATE_DEMO_NOTES = 'create_demo_notes',
  REMOVE_DEMO_NOTES = 'remove_demo_notes',
  PERSIST_CELL_ERROR = 'persist_cell_error',
  TYPECHECK_CODE_START = 'typecheck_code_start',
  TYPECHECK_CODE_COMPLETE = 'typecheck_code_complete',
  TYPECHECK_CODE_ERROR = 'typecheck_code_error',
}
